version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app-melt
    ports:
      - "5173:5173"
    volumes:
      - .:/src
      - /src/node_modules
    command: sh -c "pnpm install && pnpm dev"
